Fix TypeScript error TS2339
This is a fairly common express practice, and one that we want to tell TypeScript to explicitly ignore for now

```
error TS2339: Property 'status' does not exist on type 'Error'.
```